# Do hyperparameter setting here
vit_linear:
    lr: 0.001
    wd: 0.01
    epochs: 100
    optimizer: 'sgd'
    scheduler: 'multi_step'
    momentum: 0.99
    net_class: ViTLinear
    batch_size: 32


vit_deep:
    net_class: ViTDeep
    batch_size: 32
    lr: 0.01
    wd: 0.01
    epochs: 100
    optimizer: 'sgd'
    scheduler: 'multi_step'
    momentum : 0.9
    prompt_len: 10
    milestones: [60, 80]
    gamma: 0.1





pixmo_demo:
    lr: 0.0003
    epochs: 20
    optimizer: 'adam'
    net_class: PixMoModel
    batch_size: 16
    num_classes: 20
    
pixmo_1:
    lr: 0.0001
    epochs: 20          
    optimizer: 'adam'
    net_class: PixMoModel
    batch_size: 16
    num_classes: 20
    dropout: 0.2
    weight_decay: 0.05

pixmo_2:
    lr: 0.0001
    epochs: 20          
    optimizer: 'adam'
    net_class: PixMoModel
    batch_size: 16
    num_classes: 20
    dropout: 0.1
    weight_decay: 0.05
    num_heads: 4
    num_layers: 4
    patch_tokens: 4

pixmo_3:
    lr: 0.00015
    epochs: 30          
    optimizer: 'adamw'
    net_class: PixMoModel
    batch_size: 16
    num_classes: 20
    dropout: 0.2
    weight_decay: 0.05
    num_heads: 4
    num_layers: 4
    patch_tokens: 4